- api/controllers/user.go
- api/go.mod
- api/interfaces/init.go
- api/models/user.go
- api/routes/init.go
Close issues #1 
- Check if user exist
- Check if email exist
- Check that the fields are not empty
- Check that the email has email format
- Check that the password complies with basic rules
- Save user in mongodb
> Endpoint for user account creation

- .github/workflows/backup.yml
- algorithms/backups/backup.sh
1. Bash script to create the backup, compress the folder and upload to gdrive. 
2. Workflow to execute the bash script automatically. 
The target branch is main on purpose.
> Feat: Automate backups

- .github/workflows/integration.yml
1. Check .go files formatting to follow the go standard
2. Build go binary
3. Run tests using a "real database" using docker-compose.
I'm not sure, but i think it's not possible to test the workflow execution in this case (Because the trigger is not "workflow_call"), so, all you can do is execute some of the commands that appears in the workflow, for example, the ones in steps "💅 Check formatting", "🛫 Setup environment", "📦 Build binary" and "🧪 Run tests".
The target branch is main on purpose.
> Feat: Integration workflow

- algorithms/gyms_insertion/bulk.js
> feat: Add zones x,y coordinates as string

- .github/workflows/integration.yml
- api/.env.example
- api/utils/email.go
> Ci: email validation

- api/controllers/gyms.go
- api/models/user.go
If the user already owns the claimed item, increment the quantity instead of adding the item again to the inventory.
> Fix: Claim rewards

- .github/docs/openapi.yml
Document the API endpoints using the Open API standard. 
Go to the [Swagger Editor](https://editor.swagger.io/), paste the `.yml` file content and you should be able to preview the result on the right panel:
> Docs: Swagger

- api/controllers/session_test.go
- api/controllers/user_test.go
- api/interfaces/responses.go
- api/routes/router.go
- api/tests/tests_utils.go
Rename endpoints to follow the [JSON API recommendations](https://jsonapi.org/recommendations/).
> Refactor: Endpoints

- api/controllers/items.go
- api/controllers/loomies.go
- api/controllers/session.go
- api/controllers/user.go
- api/interfaces/responses.go
- api/middlewares/middlewares.go
- api/models/items.go
- api/models/user.go
- api/routes/router.go
To prove this, make a GET request to `/user/loomies`
Before, you must:
- Add a `owner` in some documents from collection `caught_loomies`
- Add the _id or ids in field `loomies` from `users` collection ( the id or ids are from the loomies which you add owner in the collection `caught_loomies`)
> Endpoint to obtain Loomies from an user

- .github/docs/openapi.yml
- api/controllers/loomies.go
- api/interfaces/requests.go
- api/models/loomies.go
- api/routes/router.go
Try PR:
Loomie exists:
Loomie not exists:
> Endpoint validate if Loomie still exists

- api/configuration/configuration.go
- api/controllers/gyms.go
- api/controllers/items.go
- api/controllers/loomies.go
- api/controllers/session.go
- api/controllers/user.go
- api/controllers/websocket.go
- api/controllers/zones.go
- api/interfaces/interfaces.go
- api/models/collections.go
- api/models/loomies.go
- api/models/user.go
- api/models/zones.go
- api/routes/router.go
- api/utils/email.go
- api/utils/helpers.go
- api/utils/token.go
Just check the affected endpoints still working correctly. 
Closes #82.
> Refactor: User collection and Improve naming. 

- .github/docs/openapi.yml
- api/controllers/user.go
- api/routes/router.go
> Feat: Get loomie team

- .github/docs/openapi.yml
- api/controllers/loomies.go
- api/interfaces/interfaces.go
- api/interfaces/requests.go
- api/models/loomies.go
- api/models/user.go
- api/routes/router.go
- api/utils/helpers.go
- Check User
- Check Loomie
- Insert Lommie in caught_loomies
- Add Loomie in array of loomies from user 
Example:
> Endpoint to catch a loomie

- api/controllers/gyms.go
- api/controllers/gyms_test.go
- api/controllers/user_test.go
- api/tests/tests_utils.go
| File                | Before | After |
| ------------------- | :----: | ----: |
| controllers/gyms.go |0.0%  | 82.7% |
1. Run the `go test ./...` command from the `api/` directory. 
2. (Optional 1) Run the `go test ./... -coverprofile=coverage.out` command from the `api/` directory.
3. (Optional 2) Run the `go tool cover --html=coverage.out` command from the `api/` directory to see the coverage HTML file. 
4. (Optional 3) Select the `gyms.go` file and you should see something like:
> Test: Gyms endpoints

- api/controllers/items.go
- api/controllers/items_test.go
| File                | Before | After |
| ------------------- | :----: | ----: |
| controllers/items.go |0.0%  | 76.5% |
1. Run the `go test ./...` command from the `api/` directory. 
2. (Optional 1) Run the `go test ./... -coverprofile=coverage.out` command from the `api/` directory.
3. (Optional 2) Run the `go tool cover --html=coverage.out` command from the `api/` directory to see the coverage HTML file. 
4. (Optional 3) Select the `items.go` file and you should see something like:
> Test: Items endpoints

- algorithms/database/bulk.js
- algorithms/database/models/mongoose.js
- algorithms/database/utils/utils.js
- api/interfaces/interfaces.go
- api/models/zones.go
- data/places.json
- data/static_places.json
> Feat: Multiple gyms

- algorithms/database/debug/README.md
- algorithms/database/debug/giveLoomies.js
- algorithms/database/models/mongoose.js
- algorithms/database/package.json
- algorithms/database/utils/utils.js
This utility gives all existing base Loomies with random levels to the specified user:
```bash
pnpm give:loomies <user id>
```
> Feat: Give all loomies (Debug script)

- api/controllers/loomies.go
- api/main.go
- api/models/loomies.go
- api/models/zones.go
- api/utils/helpers.go
- data/loomballs.json
- data/loomies_rarities.json
1. Change Loomballs and Loomies probabilities 
2. Remove outdated Loomies before generating new ones
3. Enable production mode on... production.
> Fix: Adjustments

- api/combat/MESSAGES_TYPES.md
- api/combat/interfaces.go
- api/controllers/websocket.go
Closes the current issues on #108.
> Fix: Combat

- api/combat/MESSAGES_TYPES.md
- api/combat/handlers.go
- api/combat/interfaces.go
Create new message type (`USER_CHANGE_LOOMIE`) to allow the players to change their current Loomie in combat.
> Feat(combat): Change player loomie

- algorithms/database/utils/utils.js
Increment the level and stats of the default gyms protectors. 
___ 
**Note:** This is just in case some one needs / wants to re-create the database. The "production protectors" were already updated with another script.
> Fix: Gyms protectors lvl

- api/combat/MESSAGES_TYPES.md
- api/combat/handlers.go
- api/combat/interfaces.go
Create USER_ESCAPE_COMBAT:
- Close combat when receiving USER_ESCAPE_COMBAT message
- Returns a message (ESCAPE_COMBAT) before closing the Websocket
> Escape from combat

- .github/docs/openapi.yml
- api/controllers/gyms.go
- api/interfaces/requests.go
- api/models/gyms.go
- api/models/user.go
- api/routes/router.go
> Feat: Update gym protectors

- api/combat/MESSAGES_TYPES.md
- api/combat/handlers.go
- api/combat/interfaces.go
Gets all the information of the entire team of loomies of the user, it is necessary to change the loomie in the front
> Get user loomies team in combat

- api/controllers/gyms.go
- api/controllers/gyms_test.go
- api/controllers/items.go
- api/controllers/items_test.go
- api/controllers/user.go
- api/controllers/user_test.go
- api/controllers/websocket.go
- api/controllers/websocket_test.go
- api/controllers/zones.go
- api/controllers/zones_test.go
| File                     | Before | After |   Change |
| ------------------------ | :----: | ----: | -------: |
| controllers/gyms.go      | 45.8%  | 82.6% | 36.8% 🟩 |
| controllers/zones.go     |  0.0%  | 81.8% | 81.8% 🟩 |
| controllers/items.go     | 21.3%  | 75.4% | 54.1% 🟩 |
| controllers/user.go      | 61.9%  | 75.3% | 13.4% 🟩 |
| controllers/websocket.go |  0.0%  |  0.0% |  36.4% 🟩 |
> Test: Controllers
